name: CI
on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        strategy:
            matrix:
                python-version: ["3.9", "3.11"]
        steps:
            - uses: actions/checkout@v4
            - name: Install Python, pipenv and Pipfile packages
              uses: kojoru/prepare-pipenv@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install package and test dependencies
              run: |
                  pipenv install pytest
                  pipenv run pip install -e .
                  pipenv --venv
            - name: Test with pytest
              run: |
                  pipenv run python -m pytest

    publish:
        needs: build
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - name: Install Python, pipenv and Pipfile packages
              uses: kojoru/prepare-pipenv@v1
            - name: Build package
              run: |
                  pipenv install build twine
                  pipenv run python -m build .
            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                  pipenv run twine upload dist/*
